services:
    distributedcache:
        container_name: distributedcache
        restart: always
        ports:
            - "6379:6379"

    api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
            - ConnectionStrings__Redis=distributedcache:6379
        depends_on:
            - distributedcache
        ports:
            - "5000:8080"
            - "5050:8081"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro